# Que. What is Numpy?
    * Ans. Numpy - Numerical Python
    * Numpy - is a python package used for computation and processing of single dimension and multi dimensional array elements.
    * Numpy was created by merging the features of ancestor modules, Numeric and Numarray, of Numpy.
    * It is an extended module of Python mainly written in C.
    * Numpy provides various functions which are capable of performing many numeric computation with High speed.
    * Numpy provides various Data Structues, implemnting multi-dimensional arrays and matrices.
    * These Data Structures are used for optimal computation regarding arrays and matrices.

# Que. What are the various Data Analysis Libraries?
Ans. The various Data Analysis libraries are:-
    1. Numpy
    2. Pandas
    3. Matplotlib

# Que. Why do we need Numpy?
    * Ans. Numpy is a Python library which provides convenient and efficient way to handle large amount of Data and is also very convenient with matrix multiplication and Data reshaping. 
    * Being fast, makes it reasonable to work with huge data.
    * Numpy in collaboration with SciPy and Matplotlib, used as a replacement to MATLAB as Python is more complete and easier programming language.

# Que. What are the advantages of using Numpy?
Ans. The advantages of using Numpy are:-
    1. Numpy performs array-oriented computation.
    2. It efficiently implements the multidimensional arrays.
    3. It perfomrs scientific computation.
    4. It is capable of perfomring Fourier Transform and reshaping the data stored in multidimensional array.
    5. Numpy provides the in-built functions for linear algebra and random number generation.

In [1]:
# !pip install numpy

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.16.2


# Creating a numpy array

In [6]:
# creating an array using list or tuple
lst = [10,23,34,56,78]
tpl = (10,23,45,45,89)






In [7]:
arr1 = np.array(lst)
arr1

array([10, 23, 34, 56, 78])

In [9]:
print(arr1, type(arr1))

[10 23 34 56 78] <class 'numpy.ndarray'>


In [10]:
arr2 = np.array(tpl)
arr2

array([10, 23, 45, 45, 89])

In [11]:
arr1.size

# No of elemets in an array

5

In [12]:
arr1.shape

# returns the shape of an arrya

(5,)

In [14]:
arr1.ndim

# returns the dimension of an array

1

In [15]:
arr1.dtype

# data type of an array elements

dtype('int64')

In [19]:
# help(np)/

In [22]:
# print(dir(arr1))

In [43]:
# Creating a 2D array

lst1 = [[10,20,30,40],[50,60,70,80.0+20j]]
arr3 = np.array(lst1)
arr3
arr3[0].itemsize

16

In [26]:
arr3.size

8

In [27]:
arr3.shape

(2, 4)

In [28]:
arr3.ndim

2

In [35]:
arr3.dtype

dtype('complex128')

In [ ]:
# int -> float -> complex -> object ----> this is called upcasting

# Creating an aray using arange function


In [ ]:
# arange is similar to range

In [48]:
arr4 = np.arange(10)
print(arr4.size, arr4.shape, arr4.ndim, arr4.dtype, arr4.itemsize)

10 (10,) 1 int64 8


In [49]:
arr5 = np.arange(1, 5, 0.5)
arr5


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [52]:
# np.array({10,20,30,10})

In [63]:
# Creating 2D array using arange function
arr6 = np.arange(1,10,0.5)
arr6


# To reshape an array, the size of an array should always be euqual to product of rows and columns




array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [72]:
arr7 = arr6.reshape(3,2,3)
arr7

array([[[1. , 1.5, 2. ],
        [2.5, 3. , 3.5]],

       [[4. , 4.5, 5. ],
        [5.5, 6. , 6.5]],

       [[7. , 7.5, 8. ],
        [8.5, 9. , 9.5]]])

In [65]:
arr6

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [70]:
arr8 = np.array([[10,20,30]])
arr8

array([[10, 20, 30]])

In [78]:
# Creating an array using linspace(start, stop, no of ele)
arr9 = np.linspace(1,10,200)
# arr9

In [82]:
# Creating an array using few more builtin functions - zeros, zeros_like, ones, ones_like, empty, eye

arr9 = np.zeros((4,4), dtype = 'int64')
arr9





array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [84]:
arr10 = np.ones((4,4), dtype = int)
arr10

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [85]:
arr11 = np.zeros_like(arr7)
arr11

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [86]:
arr11 = np.ones_like(arr7)
arr11

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
arr12 = np.empty((3,2,3))
arr12

array([[[1. , 1.5, 2. ],
        [2.5, 3. , 3.5]],

       [[4. , 4.5, 5. ],
        [5.5, 6. , 6.5]],

       [[7. , 7.5, 8. ],
        [8.5, 9. , 9.5]]])

In [91]:
arr13 = np.eye(3)
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
# Printing an array

arr14 = np.arange(3000).reshape(50,60)
arr14


array([[   0,    1,    2, ...,   57,   58,   59],
       [  60,   61,   62, ...,  117,  118,  119],
       [ 120,  121,  122, ...,  177,  178,  179],
       ...,
       [2820, 2821, 2822, ..., 2877, 2878, 2879],
       [2880, 2881, 2882, ..., 2937, 2938, 2939],
       [2940, 2941, 2942, ..., 2997, 2998, 2999]])

In [94]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [95]:
arr14

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
          33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
          55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
          71,   72,   73,   74,   75,   76,   77,   78,   79,   80,   81,
          82,   83,   84,   85,   86,   87,   88,   89,   90,   91,   92,
          93,   94,   95,   96,   97,   98,   99,  100,  101,  102,  103,
         104,  105,  106,  107,  108,  109,  110,  111,  112,  113,  114,
         115,  116,  117,  118,  119],
       [ 120,  121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
         131,  132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
         142,  143,  144,  145,  1

# Reshaping an array

In [96]:
arr15 = np.arange(15)
arr15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
arr16 = arr15.reshape(5,3)
arr16

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [98]:
arr15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
# Using shape attribute - wil make the changes to existing array
arr15.shape = 3,5

In [101]:
arr15

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
arr15.shape = 5,-1
arr15

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [106]:
arr17 = np.arange(10)

In [111]:
arr17.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [113]:
# arr17.reshape(-1,-1)

In [116]:
# Using transpose
arr20 = arr15.T

In [117]:
arr20

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [119]:
# Converting from higher dimension to 1 D array

arr21 = arr20.flatten()
arr21

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [120]:
arr20

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [122]:
arr22 = arr20.ravel()
arr22

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [123]:
arr23 = np.array([['UP', 'AP', 'MP', 'HP'],['TN', 'KL', 'KA', 'MH'],['DL', 'BH', 'WB', 'RJ']])
arr23

array([['UP', 'AP', 'MP', 'HP'],
       ['TN', 'KL', 'KA', 'MH'],
       ['DL', 'BH', 'WB', 'RJ']], dtype='<U2')

In [135]:
arr24 = arr23.flatten()    # creating a copy of an array 
arr24[0] = 100
arr24

array(['10', 'AP', 'MP', 'HP', 'TN', 'KL', 'KA', 'MH', 'DL', 'BH', 'WB',
       'RJ'], dtype='<U2')

In [136]:
arr23

array([['UP', 'AP', 'MP', 'HP'],
       ['TN', 'KL', 'KA', 'MH'],
       ['DL', 'BH', 'WB', 'RJ']], dtype='<U2')

In [137]:
arr25 = arr23.ravel()   # Creating a view of an array
arr25[0] = 100
arr25


array(['10', 'AP', 'MP', 'HP', 'TN', 'KL', 'KA', 'MH', 'DL', 'BH', 'WB',
       'RJ'], dtype='<U2')

In [138]:
arr23

array([['10', 'AP', 'MP', 'HP'],
       ['TN', 'KL', 'KA', 'MH'],
       ['DL', 'BH', 'WB', 'RJ']], dtype='<U2')

In [129]:
# d = pd.DataFrame([[10,20,30,40]])
# d.flatten()