In [1]:
import numpy as np

In [3]:
lst = [10,20,30,40]

In [4]:
lst * 2

[10, 20, 30, 40, 10, 20, 30, 40]

In [95]:
arr1 = np.array(lst)
arr1

array([10, 20, 30, 40])

In [8]:
arr1 * 2

array([20, 40, 60, 80])

In [9]:
arr2 = np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [10]:
arr1 + arr2

array([11, 22, 33, 44])

In [11]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [12]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [13]:
arr1 % arr2

array([0, 0, 0, 0])

In [19]:
arr3 = np.array([[22,33],[2,3]])
arr4 = np.array([[90,80],[2,2]])
print('ARRAY3: \n', arr3)
print()
print('ARRAY4: \n', arr4)

ARRAY3: 
 [[22 33]
 [ 2  3]]

ARRAY4: 
 [[90 80]
 [ 2  2]]


In [20]:
arr3+arr4

array([[112, 113],
       [  4,   5]])

In [21]:
arr3*arr4

array([[1980, 2640],
       [   4,    6]])

In [22]:
arr3.dot(arr4)

array([[2046, 1826],
       [ 186,  166]])

In [ ]:
1 2      4 3
3 4      2 1


((1X4)+(2X2)) ((1X3)+(2X1))
((3X4)+(2X2)) ((3X3)+(4X1))

# Compund Assignment

In [23]:
arr1

array([10, 20, 30, 40])

In [24]:
arr2

array([1, 2, 3, 4])

In [25]:
arr1 += arr2

In [26]:
arr1

array([11, 22, 33, 44])

In [27]:
arr2

array([1, 2, 3, 4])

In [28]:
arr2 *= 5

In [29]:
arr2

array([ 5, 10, 15, 20])

# Unary operations

In [96]:
arr1

array([10, 20, 30, 40])

In [70]:
np.sum(arr1)

110

In [32]:
np.max(arr1)

44

In [33]:
np.min(arr1)

11

In [97]:
sum(arr1)

100

In [98]:
arr5 = np.arange(25,55).reshape(5,6)
arr5

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [101]:
np.sum(arr5)
np.max(arr5)
np.min(arr5)

25

In [103]:
# Finding the sum of all element along the row
np.sum(arr5, axis = 1)

array([165, 201, 237, 273, 309])

In [104]:
# Finding the sum of all element along the column
np.sum(arr5, axis = 0)

array([185, 190, 195, 200, 205, 210])

In [105]:
# Finding the max of all element along the column
np.max(arr5, axis = 0)

array([49, 50, 51, 52, 53, 54])

In [ ]:
# Universal function
    np.add()
    np.mulitply()
    np.sub()
    np.div()
    np.floordiv()
    np.log()

In [ ]:
# print(dir(arr1))

In [108]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [109]:
# np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [111]:
# import math
# math.sqrt(4)

2.0

In [123]:
# Statistical Function
# mean, median, std, var


# Reading a column from a csv file using numpy
pop_data = np.genfromtxt('Data/population_2017.csv', 
                        usecols = 1,
                        delimiter = ',',
                        skip_header = 1)
pop_data



array([   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.,
        11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.,
        31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.,
        49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.,
        61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.,
       105264., 105544., 107825., 108020., 109897., 116398., 160539.,
       164229., 165314., 178844., 196440., 204327., 253045., 276244.])

In [120]:
print("Mean of Population is: ", np.mean(pop_data))
print("Median of Population is: ", np.median(pop_data))
print("Standard Deviatrion of Population is: ", np.std(pop_data))
print("Variance of Population is: ", np.var(pop_data))

Mean of Population is:  73958.12244897959
Median of Population is:  55345.0
Standard Deviatrion of Population is:  67180.61487091337
Variance of Population is:  4513235014.433986


In [ ]:
# bin() = binary_repr()

In [128]:
np.binary_repr(19)

'10011'

In [129]:
arr1


array([10, 20, 30, 40])

In [130]:
arr2

array([ 5, 10, 15, 20])

In [131]:
np.bitwise_and(arr1,arr2)

array([ 0,  0, 14,  0])

In [133]:
np.bitwise_or(arr1,arr2)

array([15, 30, 31, 60])

In [132]:
np.bitwise_xor(arr1,arr2)

array([15, 30, 17, 60])

# Indexing an dslicing

In [134]:
arr1

array([10, 20, 30, 40])

In [135]:
arr1[0]

10

In [136]:
arr1[-1]

40

In [143]:
# Slicing
arr1[1:3]
arr1[::]
arr1[::-1]

array([40, 30, 20, 10])

In [155]:
pop_data = pop_data.reshape(7,7)
pop_data

array([[   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.],
       [ 11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.],
       [ 31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.],
       [ 49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.],
       [ 61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.],
       [105264., 105544., 107825., 108020., 109897., 116398., 160539.],
       [164229., 165314., 178844., 196440., 204327., 253045., 276244.]])

In [138]:
pop_data[2][1]

33400.0

In [139]:
pop_data[2,1]

33400.0

In [145]:
# Slicing on 2D arrat
pop_data[0, ::]

array([ 792., 1300., 1618., 2910., 4049., 5177., 6320.])

In [147]:
pop_data[1:4, 1:4]

array([[11359., 11773., 14909.],
       [33400., 34571., 35446.],
       [53127., 55144., 55345.]])

In [156]:
pop_data[::, 4:]

array([[  4049.,   5177.,   6320.],
       [ 17380.,  21729.,  25398.],
       [ 37922.,  38695.,  40120.],
       [ 55641.,  56480.,  61349.],
       [ 94737., 102012., 104901.],
       [109897., 116398., 160539.],
       [204327., 253045., 276244.]])

In [157]:
pop_data[4:, 4:]

array([[ 94737., 102012., 104901.],
       [109897., 116398., 160539.],
       [204327., 253045., 276244.]])

In [158]:
pop_data

array([[   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.],
       [ 11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.],
       [ 31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.],
       [ 49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.],
       [ 61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.],
       [105264., 105544., 107825., 108020., 109897., 116398., 160539.],
       [164229., 165314., 178844., 196440., 204327., 253045., 276244.]])

In [160]:
pop_data[::2]

array([[   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.],
       [ 31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.],
       [ 61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.],
       [164229., 165314., 178844., 196440., 204327., 253045., 276244.]])

In [161]:
pop_data[::,2::2]

array([[  1618.,   4049.,   6320.],
       [ 11773.,  17380.,  25398.],
       [ 34571.,  37922.,  40120.],
       [ 55144.,  55641.,  61349.],
       [ 76965.,  94737., 104901.],
       [107825., 109897., 160539.],
       [178844., 204327., 276244.]])

In [162]:
pop_data[::2,2::2]

array([[  1618.,   4049.,   6320.],
       [ 34571.,  37922.,  40120.],
       [ 76965.,  94737., 104901.],
       [178844., 204327., 276244.]])

In [163]:
pop_data[::-1, ::-1]

array([[276244., 253045., 204327., 196440., 178844., 165314., 164229.],
       [160539., 116398., 109897., 108020., 107825., 105544., 105264.],
       [104901., 102012.,  94737.,  84287.,  76965.,  73925.,  61559.],
       [ 61349.,  56480.,  55641.,  55345.,  55144.,  53127.,  49290.],
       [ 40120.,  38695.,  37922.,  35446.,  34571.,  33400.,  31196.],
       [ 25398.,  21729.,  17380.,  14909.,  11773.,  11359.,  11192.],
       [  6320.,   5177.,   4049.,   2910.,   1618.,   1300.,    792.]])

In [164]:
population = pop_data.flatten()

In [165]:
population

array([   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.,
        11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.,
        31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.,
        49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.,
        61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.,
       105264., 105544., 107825., 108020., 109897., 116398., 160539.,
       164229., 165314., 178844., 196440., 204327., 253045., 276244.])

In [169]:
# data = population[32], population[33], population[34]
# data

(94737.0, 102012.0, 104901.0)

In [179]:
my_arr = np.arange(25,55).reshape(5,6)
my_arr

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [178]:
row_arr = np.array([2,3,2,1])
row_arr

array([2, 3, 2, 1])

In [181]:
col_arr = np.array([1,2,3,1])
col_arr

array([1, 2, 3, 1])

In [182]:
my_arr[row_arr, col_arr]

array([38, 45, 40, 32])

In [186]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [183]:
row_arr = np.array([0,1,1,2])
row_arr

array([0, 1, 1, 2])

In [184]:
col_arr = np.array([2,1,3,2])
col_arr

array([2, 1, 3, 2])

In [188]:
fruit[row_arr, col_arr] = 'Cillies'

In [189]:
fruit

array([['Banana', 'Mango', 'Cillies', 'Avacado'],
       ['Papaya', 'Cillies', 'Plum', 'Cillies'],
       ['Apricot', 'Apple', 'Cillies', 'Black berry']], dtype='<U11')

# Indexing using masked array

In [190]:
pop_data

array([[   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.],
       [ 11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.],
       [ 31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.],
       [ 49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.],
       [ 61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.],
       [105264., 105544., 107825., 108020., 109897., 116398., 160539.],
       [164229., 165314., 178844., 196440., 204327., 253045., 276244.]])

In [193]:
pop_data[(pop_data>84287)==False]

array([  792.,  1300.,  1618.,  2910.,  4049.,  5177.,  6320., 11192.,
       11359., 11773., 14909., 17380., 21729., 25398., 31196., 33400.,
       34571., 35446., 37922., 38695., 40120., 49290., 53127., 55144.,
       55345., 55641., 56480., 61349., 61559., 73925., 76965., 84287.])

In [192]:
pop_data>84287

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [197]:
np.sum((pop_data>84287)==False)

32

In [198]:
np.any(pop_data>84287)

True

In [199]:
np.all(pop_data>84287)

False

In [200]:
np.count_nonzero(pop_data>84287)

17

In [201]:
pop_data[(pop_data>84287)==False] = 0

In [202]:
pop_data

array([[     0.,      0.,      0.,      0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,      0.,      0.,      0.],
       [     0.,      0.,      0.,      0.,  94737., 102012., 104901.],
       [105264., 105544., 107825., 108020., 109897., 116398., 160539.],
       [164229., 165314., 178844., 196440., 204327., 253045., 276244.]])