In [3]:
import numpy as np

In [4]:
arr= np.arange(1,10)

In [102]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x=arr.copy()

In [119]:
print(x.base)

None


In [106]:
x[0]=10

In [107]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
x

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [110]:
y=arr.view()

In [111]:
# y[0]=11

In [120]:
print(y.base)

[11  2  3  4  5  6  7  8  9]


In [114]:
arr

array([11,  2,  3,  4,  5,  6,  7,  8,  9])

In [116]:
print(x.base)

None


In [117]:
print(y.base)

[11  2  3  4  5  6  7  8  9]


In [123]:
arr=np.array([1], ndmin=3)

In [125]:
arr.shape

(1, 1, 1)

In [126]:
arr.itemsize

4

In [127]:
arr

array([[[1]]])

In [155]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [156]:
arr2=np.array([[10,20,30,40],[11,22,33,44]])
arr2

array([[10, 20, 30, 40],
       [11, 22, 33, 44]])

In [148]:
arr3=np.concatenate((arr1,arr2),axis=0)

In [149]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [11, 22, 33, 44]])

In [153]:
arr3=np.concatenate((arr1,arr2),axis=1)
arr3

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 11, 22, 33, 44]])

In [158]:
arr3=np.stack((arr1,arr2),axis=0)
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [11, 22, 33, 44]]])

In [160]:
arr3=np.stack((arr1,arr2),axis=1)
arr3

array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[ 5,  6,  7,  8],
        [11, 22, 33, 44]]])

In [169]:
# arr8= np.array([1,2,3,4,5,6])

In [173]:
# arr9=np.array_split(arr8, 5)

In [175]:
# print(arr9)

In [6]:
arr8= np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])

In [7]:
arr9=np.array_split(arr8,2, axis=0)

In [8]:
print(arr9)

[array([[1, 2, 3, 4, 5, 6]]), array([[11, 12, 13, 14, 15, 16]])]


In [9]:
arr9=np.array_split(arr8,3, axis=1)

In [10]:
arr9

[array([[ 1,  2],
        [11, 12]]),
 array([[ 3,  4],
        [13, 14]]),
 array([[ 5,  6],
        [15, 16]])]

In [ ]:
arr8= np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])

In [11]:
arr11=np.hsplit(arr8,2)

In [12]:
arr11

[array([[ 1,  2,  3],
        [11, 12, 13]]),
 array([[ 4,  5,  6],
        [14, 15, 16]])]

In [13]:
arr12=np.vsplit(arr8,2)

In [14]:
arr12

[array([[1, 2, 3, 4, 5, 6]]), array([[11, 12, 13, 14, 15, 16]])]

In [23]:
arr13=np.vstack(arr8)

In [24]:
arr13

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [63]:
arr14=np.vstack(arr8)

In [64]:
arr14

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [38]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])

In [39]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]


In [52]:
arr14=np.hsplit(arr,2)

In [53]:
print(arr14)

[array([[[ 1,  2,  3,  4]],

       [[10, 20, 30, 40]]]), array([[[ 5,  6,  7,  8]],

       [[50, 60, 70, 80]]])]


In [56]:
arr14=np.vsplit(arr,2)

In [57]:
print(arr14)

[array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]]), array([[[10, 20, 30, 40],
        [50, 60, 70, 80]]])]
